### ISSUE TITLE
This addon is 

### ISSUE THREAD

**Issue by rlust** [hassio-addons/addon-firefly-iii#1]
# Problem/Motivation
This addon is not available in the repository.
I cannot add this.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Correct, it has not been released yet.
