### ISSUE TITLE
CSV importer removed?

### ISSUE THREAD

**Issue by excalbian** [hassio-addons/addon-firefly-iii#10]
# Problem/Motivation

> Trying to understand why the CSV importer was removed?

## Expected behavior

> My use case for Firefly needs the CSV importer.

## Actual behavior

> Without it, I can't (easily) import transactions.

## Proposed changes

> Can we just add the csv-importer back?

**Comment by sinclairpaul** [comment]
See the release notes upstream https://github.com/firefly-iii/firefly-iii/releases/tag/5.2.0 , the functionality was removed from the app in favor of standalone variants, which at this point you would need to run yourself.

<blockquote><img src="https://repository-images.githubusercontent.com/21298446/b3a9ec00-3e68-11ea-91fa-f4c512995087" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/firefly-iii/firefly-iii">firefly-iii/firefly-iii</a></strong></div><div>Firefly III: a personal finances manager. Contribute to firefly-iii/firefly-iii development by creating an account on GitHub.</div></blockquote>
