### ISSUE TITLE
When this addon will be released?

### ISSUE THREAD

**Issue by niccolobusato** [hassio-addons/addon-firefly-iii#3]
Just asking if anyone knows when this will be available!

btw. thanks for your work :)

**Comment by reharmsen** [comment]
@niccolobusato 
If you really want to try this addon, you could add the edge repository to your configuration, and install from there. (I did, to try this addon)

**Comment by niccolobusato** [comment]
@reharmsen which url should i add? this one? https://github.com/hassio-addons/addon-firefly-iii

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-firefly-iii">hassio-addons/addon-firefly-iii</a></strong></div><div>Firefly-III - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-firefly-iii</div></blockquote>

**Comment by Nanianmichaels** [comment]
You want to follow the instructions here: https://github.com/hassio-addons/repository-edge

Then install Firefly from the new section that will appear on the addons page on HA.

I have installed it already, though I didn't have the time to properly configure it, so I can't give feedback just yet.

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository-edge">hassio-addons/repository-edge</a></strong></div><div>EDGE - Community Hass.io Add-ons for Home Assistant - hassio-addons/repository-edge</div></blockquote>

**Comment by niccolobusato** [comment]
thank you! :) @Nanianmichaels @reharmsen

**Comment by frenck** [comment]
Please note, edge add-on contains a development version. It is not recommended to actually use this for "production".
