### ISSUE TITLE
Seems like firefly has no permission to write

### ISSUE THREAD

**Issue by JHeijting** [hassio-addons/addon-firefly-iii#7]
First of all I know that edge add-ons are not intended to use in production. However, I really don't understand the installation instructions from Firefly.
And than there is this great add-on. It's very easy and userfriendly; **great work!**

**Problem**
Somehow I can't import any CSV files anymore. This has been working flawlessly before (in fact, I haven't found any issue besides this one yet).

**Expected behaviour**
Being able to select an import file and configuration file. Than upload them to Firefly III.

**Actual behavior**
I get an error: _Failed to open stream: Permission denied_
More specific information about the error can be found here: https://github.com/firefly-iii/firefly-iii/issues/3239

**Comment by JHeijting** [comment]
I think I have found the cause of this problem. It might not be caused by permissions, but by the names of the CSV and config files. I reported the work around on the Firefly III issue: https://github.com/firefly-iii/firefly-iii/issues/3239#issuecomment-610226268

**Comment by sinclairpaul** [comment]
If you can post samples of the files with issues, I can take a look still.  According to the comments this shouldn't occur, so could possibly be something in nginx/php.

**Comment by JHeijting** [comment]
Thank you for your response. I wrongly assumed that the upload worked. Whenever I upload a file (even one that worked fine before) it doesn't work. Somehow when I do not upload a configuration file I get passed the error, but then no columns in the CSV are detected.

It is a CSV in UTF8 format.

**Comment by sinclairpaul** [comment]
I cannot duplicate the issue as imports are working fine for me.  To duplicate I need some form of dummy data that you can share with steps to reproduce.

**Comment by JHeijting** [comment]
This dummy data is not working on my import.
1. I go to import transactions;
2. Import file;
3. Choose the import file;
4. Optional: choose the configuration file (with or without, both not working);
5. I receive the error _Failed to open stream: Permission denied_.

[Dummy data.zip](https://github.com/hassio-addons/addon-firefly-iii/files/4448793/Dummy.data.zip)

**Comment by sinclairpaul** [comment]
Once I fixed the CSV formatting of the import file, I can import fine.

At which stage do you see the error?

**Comment by JHeijting** [comment]
Thanks for looking in to this. I receive the error after selecting the files to upload and than when I press the green button 'upload files'.

**Comment by sinclairpaul** [comment]
I cannot duplicate even with your data, just to rule out any differences, what is your platform you are running on, and are your running the app in a different locale?

**Comment by JHeijting** [comment]
I'm running Firefly III 5.1.1 using the Edge add-on (0094e85) on HASSIO 0.107.7. Default settings with the stable MariaDB add-on v2.1.1

**Comment by sinclairpaul** [comment]
Which hardware platform?  Can you post the addon log when the upload occurs, I am most interested if you can capture the nginx post.

**Comment by JHeijting** [comment]
I run it on VMware ESXi on Debian GNU/Linux 10 (buster).

This is the addon log:
`[17:39:24] INFO: Starting PHP-FPM...
[17:39:24] INFO: Starting NGinx...
[09/Apr/2020:17:39:35 +0200] 302 -(172.26.6.132) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:35 +0200] 200 -(172.26.6.132) GET /login HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:37 +0200] 302 -(172.26.6.132) POST /login HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:37 +0200] 200 -(172.26.6.132) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:37 +0200] 200 -(172.26.6.132) GET /v1/jscript/variables?ext=.js&v=5.1.1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /chart/account/frontpage HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /chart/budget/frontpage HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /chart/category/frontpage HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /json/box/balance HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /chart/account/revenue HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /json/box/bills HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /json/box/available HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /json/frontpage/piggy-banks HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /json/box/net-worth HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:38 +0200] 200 -(172.26.6.132) GET /chart/account/expense HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:40 +0200] 200 -(172.26.6.132) GET /import HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:40 +0200] 200 -(172.26.6.132) GET /v1/jscript/variables?ext=.js&v=5.1.1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:41 +0200] 302 -(172.26.6.132) GET /import/create/file HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:41 +0200] 200 -(172.26.6.132) GET /import/job/configuration/XAGL7Er3HVFg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:41 +0200] 200 -(172.26.6.132) GET /v1/jscript/variables?ext=.js&v=5.1.1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)
[09/Apr/2020:17:39:48 +0200] 500 -(172.26.6.132) POST /import/job/configuration/XAGL7Er3HVFg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)`

This is the info from Firefly III:
`Error
This error occured in file /var/www/firefly/vendor/league/flysystem/src/Adapter/Local.php on line 135 with code 0.

Stack trace
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/firefl...', 135, Array)
#1 /var/www/firefly/vendor/league/flysystem/src/Adapter/Local.php(135): file_put_contents('/data/firefly/u...', '"IBAN/BBAN,""Mu...', 2)
#2 /var/www/firefly/vendor/league/flysystem/src/Filesystem.php(102): League\Flysystem\Adapter\Local->write('at-84.data', '"IBAN/BBAN,""Mu...', Object(League\Flysystem\Config))
#3 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(225): League\Flysystem\Filesystem->put('at-84.data', '"IBAN/BBAN,""Mu...', Object(League\Flysystem\Config))
#4 /var/www/firefly/app/Repositories/ImportJob/ImportJobRepository.php(447): Illuminate\Filesystem\FilesystemAdapter->put('at-84.data', '"IBAN/BBAN,""Mu...')
#5 /var/www/firefly/app/Http/Controllers/Import/JobConfigurationController.php(147): FireflyIII\Repositories\ImportJob\ImportJobRepository->storeFileUpload(Object(FireflyIII\Models\ImportJob), 'import_file', Object(Illuminate\Http\UploadedFile))
#6 [internal function]: FireflyIII\Http\Controllers\Import\JobConfigurationController->post(Object(Illuminate\Http\Request), Object(FireflyIII\Models\ImportJob))
#7 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#8 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('post', Array)
#9 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\Import\JobConfigurationController), 'post')
#10 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#11 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#12 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/firefly/app/Http/Controllers/Import/JobConfigurationController.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(153): FireflyIII\Http\Controllers\Import\JobConfigurationController->FireflyIII\Http\Controllers\Import\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/firefly/app/Http/Controllers/Controller.php(96): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(153): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#17 /var/www/firefly/app/Http/Middleware/InterestingMessage.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\InterestingMessage->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /var/www/firefly/app/Http/Middleware/Binder.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/firefly/app/Http/Middleware/Range.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/firefly/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): PragmaRX\Google2FALaravel\Middleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/firefly/app/Http/Middleware/Authenticate.php(73): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/firefly/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/firefly/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/firefly/app/Http/Middleware/Sandstorm.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Sandstorm->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#44 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#45 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#46 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#47 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/firefly/app/Http/Middleware/InstallationId.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\InstallationId->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/firefly/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/firefly/app/Http/Middleware/SecureHeaders.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\SecureHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /var/www/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /var/www/firefly/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}`

**Comment by sinclairpaul** [comment]
The only other thing I can possibly think of is maybe the file naming particularly the data files (although not sure if relevant, but maybe an outcome from when I switched from SQLLite to MySQL).  The files on you host (assuming default install) will be at /usr/share/hassio/addons/data/40817795_firefly-iii/firefly/upload.

You could possibly try moving these out and retrying, I would recommend a snapshot beforehand.
