### ISSUE TITLE
Maps not showing / Location cannot be set for tags

### ISSUE THREAD

**Issue by marecabo** [hassio-addons/addon-firefly-iii#8]
# Problem/Motivation

A location can be assigned to a tag in Firefly III and a map can be shown of that location on the tag's page if a Mapbox API key is configured. See [Tags - Firefly III Documentation](https://docs.firefly-iii.org/concepts/tags) for details.

As there is no Mapbox API key available to the addon, locations cannot be added to tags and a map for tags with a location already assigned does not show.

![image](https://user-images.githubusercontent.com/23156476/83326588-8f767580-a275-11ea-97ba-46fb0028b7a4.png)
This is the message which appears instead of the location input field when creating a tag.

There is currently no option to specify one's individual Mapbox API key in the options to pass it to the addon, but it would be great if there would be one.

## Expected behavior

The addon allows to edit/add locations of tags and shows their location on a map.

## Actual behavior

The addon does not show a map with the tag's location.

## Steps to reproduce

Create a tag and attempt to assign a location to it.

## Proposed changes

I followed the official addon developer documentation to add a `mapbox_api_key` option here: 
https://github.com/marecabo/addon-firefly-iii/commit/3bf16ac1354397064f51e6c3ed1307bbc9c94b34

**Comment by sinclairpaul** [comment]
Closed by #9 😄
